openapi: 3.0.1
info:
  title: FRIDA PensionSerivce
  description: 
    $ref: './docs/FRIDA_PensionInformation_OA3/description_de.md'
  contact:
    $ref: './docs/FRIDA_PensionInformation_OA3/FRIDA_PensionInformation_OA3_full_en.yaml#/info/contact'
  license:
    $ref: './docs/FRIDA_PensionInformation_OA3/FRIDA_PensionInformation_OA3_full_en.yaml#/info/license'
  version: 
    $ref: './docs/FRIDA_PensionInformation_OA3/FRIDA_PensionInformation_OA3_full_en.yaml#/info/version'
externalDocs:
  $ref: './docs/FRIDA_PensionInformation_OA3/FRIDA_PensionInformation_OA3_full_en.yaml#/externalDocs'

paths:
  $ref: './docs/FRIDA_PensionInformation_OA3/FRIDA_PensionInformation_OA3_full_en.yaml#/paths'
components:
  $ref: './docs/FRIDA_PensionInformation_OA3/FRIDA_PensionInformation_OA3_full_en.yaml#/components'